doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '18'
        charset: utf8

    orm:
        enable_native_lazy_objects: true

        default_entity_manager: default

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

                mappings:
                    Identity:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Domain/Identity/Entity'
                        prefix: 'Domain\Identity\Entity'
                        is_bundle: false

                    Dashboard:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Domain/Dashboard/Entity'
                        prefix: 'Domain\Dashboard\Entity'
                        is_bundle: false
