security:
    # Password hasher
    password_hashers:
        Domain\Identity\Entity\User:
            algorithm: auto

    # Provider personnalisé
    providers:
        app_user_provider:
            id: Infrastructure\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Logout seulement
            logout:
                path: logout
                target: logout_success

    # Contrôle d'accès
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/two-factor, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10