parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/'
            - '../src/Application/'   
            - '../src/Infrastructure/'   
            - '../src/UI/'           
            - '../src/Kernel.php'

    Domain\:
        resource: '../src/Domain/'

    Application\:
        resource: '../src/Application/'

    Infrastructure\:
        resource: '../src/Infrastructure/'

    UI\:
        resource: '../src/UI/'


    Domain\Identity\Repository\UserRepositoryInterface:
        alias: Infrastructure\Doctrine\Repository\UserRepository

    Domain\Identity\Repository\TwoFactorCodeRepositoryInterface:
        alias: Infrastructure\Doctrine\Repository\TwoFactorCodeRepository

    Domain\Identity\Repository\LoginAttemptRepositoryInterface:
        alias: Infrastructure\Doctrine\Repository\LoginAttemptRepository

    Domain\Dashboard\Repository\DashboardRepositoryInterface:
        alias: Infrastructure\Doctrine\Repository\DashboardRepository